import { Metadata } from "next";
import "../styles/global.css";
import Navigatoin from "../components/navigation";

export const metadata: Metadata = {
  title: {
    template: "%s | Next Movies",
    default: "Loading...",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigatoin />
        {children}
      </body>
    </html>
  );
}
